# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5928a0de3b4adc672805eef3918467151b3c45ab7336d3c323c6d156410382f940da92f9b401dc96491c214e8c68f4cf9f9714c5d2fe259d9f578ff74a381759

test:
  secret_key_base: 17803fccb171fa5716ae14c62e747ed9b6915da467b01c93550441ead9053538adcbe206942b44f9d8d3209ffc1bbf63ee31c8f93589f243062fa5306b0654dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
